
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Feb 07 10:51:58 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_CONST = 44;
  public static final int CONST = 42;
  public static final int LESS_THAN_OR_EQUAL = 16;
  public static final int NOT_EQUAL = 12;
  public static final int LPAREN = 25;
  public static final int SEMI = 24;
  public static final int CONTINUE = 9;
  public static final int NUM_CONST = 43;
  public static final int MINUS = 31;
  public static final int GREATER_THAN = 13;
  public static final int RPAREN = 26;
  public static final int AND = 17;
  public static final int OR = 18;
  public static final int COMMA = 38;
  public static final int CLASS = 3;
  public static final int INC = 36;
  public static final int DIV = 33;
  public static final int PLUS = 30;
  public static final int ASSIGN = 29;
  public static final int IF = 5;
  public static final int EOF = 0;
  public static final int RETURN = 7;
  public static final int EQUAL = 11;
  public static final int NEW = 37;
  public static final int LAMBDA = 20;
  public static final int error = 1;
  public static final int MUL = 32;
  public static final int MOD = 34;
  public static final int IDENT = 46;
  public static final int BREAK = 2;
  public static final int VOID = 41;
  public static final int FOREACH = 10;
  public static final int COLON = 19;
  public static final int LBRACE = 22;
  public static final int ELSE = 4;
  public static final int LSQUARE = 27;
  public static final int READ = 39;
  public static final int RSQUARE = 28;
  public static final int WHILE = 6;
  public static final int RBRACE = 23;
  public static final int EXTENDS = 8;
  public static final int PROG = 21;
  public static final int BOOL_CONST = 45;
  public static final int GREATER_THAN_OR_EQUAL = 14;
  public static final int DEC = 35;
  public static final int LESS_THAN = 15;
  public static final int PRINT = 40;
}

